---
argument_specs:
  main:
    options:
      apt_repositories:
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
          file:
            required: false
            type: str
          url:
            required: true
            type: str
          distribution:
            required: false
            type: str
          components:
            required: true
            type: list
            elements: str
          state:
            required: false
            type: str
