---
argument_specs:
  main:
    options:
      apt_repositories:
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
          file:
            type: str
          url:
            required: true
            type: str
          distribution:
            type: str
          components:
            required: true
            type: list
            elements: str
          state:
            type: str
            choices:
              - absent
              - present
      apt_repositories_force_apt_get:
        type: bool
      apt_repositories_empty_sources_list:
        type: bool
      apt_repositories_sources_list_configuration_file:
        type: str
      apt_repositories_sources_list_dot_d_configuration_directory:
        type: str
