---
namespace: "damex"
name: "apt"
version: "0.1.4"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <damex.pp@icloud.com>"
license_file: "LICENSE"
tags:
  - "apt"
repository: "https://github.com/damex/ansible-collections-apt"
