---
namespace: damex
name: apt
version: 0.1.9
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
license_file: LICENSE
tags:
  - apt
repository: https://github.com/damex/ansible-collections-apt
