---
namespace: damex
name: apt
version: 1.2.2
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: apt collection
license_file: LICENSE
tags:
  - apt
  - linux
  - system
repository: https://github.com/damex/ansible-collections-apt
issues: https://github.com/damex/ansible-collections-apt/issues
