---
- name: Ensure apt repositories
  tags:
    - apt
    - apt_repositories
  block:
    - name: Ensure apt repositories sources.list is empty
      ansible.builtin.import_tasks: empty_sources_list.yml
    - name: Ensure apt repositories
      ansible.builtin.import_tasks: repositories.yml
