---
argument_specs:
  main:
    options:
      apt_packages:
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
          version:
            type: str
          default_release:
            type: str
          install_recommends:
            type: bool
          allow_downgrade:
            type: bool
          purge:
            type: bool
          force_apt_get:
            type: bool
          lock_timeout:
            type: int
          state:
            type: str
            choices:
              - absent
              - present
      apt_packages_state:
        type: str
        choices:
          - absent
          - present
      apt_packages_install_recommends:
        type: bool
      apt_packages_allow_downgrade:
        type: bool
      apt_packages_purge:
        type: bool
      apt_packages_force_apt_get:
        type: bool
      apt_packages_lock_timeout:
        type: int
