---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: apt packages role
  license: GPLv2
  min_ansible_version: 2.12.0
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
dependencies:
  - damex.apt.apt_cache
