---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: apt packages role
  license: GPLv2
  min_ansible_version: 2.14.2
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies:
  - name: damex.apt.apt_cache
