---
- name: Ensure apt package {{ apt_package_name }}
  ansible.builtin.apt:
    pkg: "{% if apt_package_version and apt_package_version | length and apt_package_version != 'latest' %}{{ apt_package_name }}={{ apt_package_version }}{% else %}{{ apt_package_name }}{% endif %}"
    default_release: "{{ apt_package_default_release | default(omit) }}"
    allow_downgrade: "{{ apt_package_allow_downgrade }}"
    install_recommends: "{{ apt_package_install_recommends }}"
    purge: "{{ apt_package_purge }}"
    force_apt_get: "{{ apt_package_force_apt_get }}"
    lock_timeout: "{{ apt_package_lock_timeout }}"
    state: "{% if apt_package_version == 'latest' and apt_package_state == 'present' %}latest{% else %}{{ apt_package_state }}{% endif %}"
  become: true
