---
argument_specs:
  main:
    options:
      apt_keys:
        type: list
        required: true
        elements: dict
        options:
          id:
            required: true
            type: str
          url:
            required: true
            type: str
          state:
            required: false
            type: str
      apt_keys_state:
        type: str
        required: false
        default: present
        choices:
          - absent
          - present
