---
argument_specs:
  main:
    options:
      apt_keys:
        type: list
        elements: dict
        options:
          id:
            required: true
            type: str
          url:
            required: true
            type: str
          state:
            type: str
            choices:
              - absent
              - present
      apt_keys_state:
        type: str
        choices:
          - absent
          - present
