---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: apt cache role
  license: GPLv2
  min_ansible_version: 2.12.0
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal
dependencies: []
