---
argument_specs:
  main:
    options:
      apt_preferences:
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
          package_name:
            type: str
          package_names:
            type: list
            elements: str
          pin:
            required: true
            type: str
          pin_priority:
            required: true
            type: int
          state:
            type: str
            choices:
              - absent
              - present
