---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: apt preferences role
  license: GPLv2
  min_ansible_version: 2.19.0
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: damex.apt.apt_cache
